base_url = "https://jarp0l.github.io/apolloX/"
title = "apolloX"
build_search_index = false
compile_sass = true
minify_html = true
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "dracula"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"

menu = [
    { name = "/all_posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/feed", url = "/atom.xml", weight = 4 },
]

# socials = [
#    { name = "twitter", url = "https://twitter.com/not_matthias", icon = "twitter" },
#    { name = "github", url = "https://github.com/not-matthias/", icon = "github" },
# ]

custom_css = []
